server:
  #servlet-path: /boot
  context-path: /boot
  #tomcat:
    #redirect-context-root: true
    
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:~/learning
    name: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
  
#Global      
email: aaaa@jda.com

app:
    menus:
    - title: Home
      name: Home
      path: /
    - title: Login
      name: Login
      path: /login
      
    error: /error        

      