server:
  context-path: /bootthyme
 
spring:      
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:~/learning
    name: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
  
#Global      
email: aaaa@jda.com

app:
    menus:
    - title: Home
      name: Home
      path: /
    - title: Login
      name: Login
      path: /login
      
    error: /error        

      